Permission.create!([
  {name: "Crear Carrito", description: "Permite crear un carrito.", action: "create", controller: "Carts"},
  {name: "Destruir Carrito", description: "Permite destruir un carrito.", action: "destroy", controller: "Carts"},
  {name: "Editar Carrito", description: "Permite visualizar la vista editar carrito.", action: "edit", controller: "Carts"},
  {name: "Mostrar Listado De Carritos", description: "Permite mostrar un listado de los carritos.", action: "index", controller: "Carts"},
  {name: "Nuevo Carrito", description: "Permite visualizar la vista nuevo carrito.", action: "new", controller: "Carts"},
  {name: "Mostrar Detalles De Un Carrito", description: "Permite mostrar los detalles de un carrito.", action: "show", controller: "Carts"},
  {name: "Actualizar Carrito", description: "Permite actualizar un carrito. ", action: "update", controller: "Carts"},
  {name: "Crear Orden", description: "Permite crear una orden.", action: "create", controller: "Orders"},
  {name: "Destruir Orden", description: "Permite destruir una orden.", action: "destroy", controller: "Orders"},
  {name: "Editar Orden", description: "Permite visualizar la vista editar orden.", action: "edit", controller: "Orders"},
  {name: "Mostrar Listado De Ordenes", description: "Permite mostrar un listado de las ordenes.", action: "index", controller: "Orders"},
  {name: "Nueva Orden", description: "Permite visualizar la vista nueva orden.", action: "new", controller: "Orders"},
  {name: "Mostrar Detalles De Una Orden", description: "Permite mostrar los detalles de una orden.", action: "show", controller: "Orders"},
  {name: "Actualizar Orden", description: "Permite actualizar una orden.", action: "update", controller: "Orders"},
  {name: "Crear Permiso", description: "Permite crear un permiso.", action: "create", controller: "Permissions"},
  {name: "Desturi Permiso", description: "Permite destruir un permiso.", action: "destroy", controller: "Permissions"},
  {name: "Generar Semillas", description: "Permite generar las semillas de los permisos y sus relaciones.", action: "generate_seeds", controller: "Permissions"},
  {name: "Obtener Controladores Y Acciones", description: "Permite obtener los controladores y acciones para generar los permisos.", action: "get_controller_actions", controller: "Permissions"},
  {name: "Crear Producto", description: "Permite crear un producto.", action: "create", controller: "Products"},
  {name: "Asignar Permisos A Roles", description: "Permite asignar permisos a un rol existente. ", action: "assign_permissions", controller: "Roles"},
  {name: "Mostrar Permisos Asignados A Un Rol", description: "Permite mostrar los permisos asignados de un rol.", action: "role_permissions", controller: "Roles"},
  {name: "Crear Usuario", description: "Permite crear un usuario.", action: "create_user", controller: "Users::Registrations"},
  {name: "Editar Un Usuario", description: "Permite visualizar la vista editar de un usuario.", action: "edit_user", controller: "Users::Registrations"},
  {name: "Mostrar Listado De Usuarios", description: "Permite mostrar un listado de los usuarios.", action: "index", controller: "Users::Registrations"},
  {name: "Nuevo Usuario", description: "Permite visualizar la vista nuevo usuario.", action: "new_user", controller: "Users::Registrations"},
  {name: "Mostrar Detalles De Un Usuario", description: "Permite mostrar los detalles de un usuario.", action: "show", controller: "Users::Registrations"},
  {name: "Actualizar Usuario", description: "Permite actualizar un usuario.", action: "update_user", controller: "Users::Registrations"},
  {name: "Editar Permiso", description: "Permite visualizar la vista editar permiso.", action: "edit", controller: "Permissions"},
  {name: "Mostrar Listado De Permisos", description: "Permite mostrar un listado de los permisos.", action: "index", controller: "Permissions"},
  {name: "Nuevo Permiso", description: "Nuevo Carrito Permite visualizar la vista nuevo permiso.", action: "new", controller: "Permissions"},
  {name: "Mostrar Detalles De Un Permiso", description: "Permite mostrar los detalles de un permiso.", action: "show", controller: "Permissions"},
  {name: "Actualizar Permiso", description: "Permite actualizar un permiso.", action: "update", controller: "Permissions"},
  {name: "Destruir Producto", description: "Permite destruir un producto.", action: "destroy", controller: "Products"},
  {name: "Editar Producto", description: "Permite visualizar la vista editar producto.", action: "edit", controller: "Products"},
  {name: "Mostrar Listado De Productos", description: "Permite mostrar un listado de los productos.", action: "index", controller: "Products"},
  {name: "Nuevo Producto", description: "Permite visualizar la vista nuevo producto.", action: "new", controller: "Products"},
  {name: "Mostrar Detalles De Un Producto", description: "Permite mostrar los detalles de un producto.", action: "show", controller: "Products"},
  {name: "Actualizar Producto", description: "Permite actualizar un producto.", action: "update", controller: "Products"},
  {name: "Crear Restaurante", description: "Permite crear un restaurante.", action: "create", controller: "Restaurants"},
  {name: "Destruir Restaurante", description: "Permite destruir un restaurante.", action: "destroy", controller: "Restaurants"},
  {name: "Editar Restaurante", description: "Permite visualizar la vista editar restaurante.", action: "edit", controller: "Restaurants"},
  {name: "Mostrar Listado De Restaurantes", description: "permite mostrar un listado de los restaurantes.", action: "index", controller: "Restaurants"},
  {name: "Nuevo Restaurante", description: "Permite visualizar la vista nuevo restaurante.", action: "new", controller: "Restaurants"},
  {name: "Mostrar Detalles De Un Restaurante", description: "Permite mostrar los detalles de un restaurante.", action: "show", controller: "Restaurants"},
  {name: "Actualizar Restaurante", description: "Permite actualizar un restaurante.", action: "update", controller: "Restaurants"},
  {name: "Crear Rol", description: "Permite crear un rol.", action: "create", controller: "Roles"},
  {name: "Destruir Rol", description: "Permite destruir un rol.", action: "destroy", controller: "Roles"},
  {name: "Editar Rol", description: "Permite visualizar la vista editar rol.", action: "edit", controller: "Roles"},
  {name: "Mostrar Listado De Roles", description: "Permite mostrar un listado de los roles.", action: "index", controller: "Roles"},
  {name: "Nuevo Rol", description: "Permite visualizar la vista nuevo rol.", action: "new", controller: "Roles"},
  {name: "Mostrar Detalles De Un Rol", description: "Permite mostrar los detalles de un rol.", action: "show", controller: "Roles"},
  {name: "Actualizar Rol", description: "Permite actualizar un rol.", action: "update", controller: "Roles"},
  {name: "Listado De Productos De Un Restaurante", description: "Listado de productos de un restaurante", action: "dishes", controller: "Restaurants"},
  {name: "Agregar Producto", description: "Agregar producto", action: "add_product_to_cart", controller: "Products"},
  {name: "Eliminar Producto Del Carro", description: "Eliminar producto del carro", action: "delete_product_from_cart", controller: "Products"},
  {name: "Remover Uno A La Cantidad Del Producto Del Carro", description: "Remover uno a la cantidad del producto del carro", action: "one_less_product", controller: "Products"},
  {name: "Cantidad Custom De Producto En El Carro", description: "Cantidad custom de producto en el carro", action: "set_quantity", controller: "Products"},
  {name: "Ver Carro De Usuario", description: "Ver carro de usuario", action: "user_cart", controller: "Carts"}
])
