PermissionRole.create!([
  {role_id: 2, permission_id: 13},
  {role_id: 2, permission_id: 37},
  {role_id: 2, permission_id: 19},
  {role_id: 2, permission_id: 33},
  {role_id: 2, permission_id: 34},
  {role_id: 2, permission_id: 35},
  {role_id: 2, permission_id: 36},
  {role_id: 2, permission_id: 38},
  {role_id: 3, permission_id: 6},
  {role_id: 3, permission_id: 7},
  {role_id: 3, permission_id: 3},
  {role_id: 3, permission_id: 11},
  {role_id: 3, permission_id: 8},
  {role_id: 3, permission_id: 12},
  {role_id: 3, permission_id: 13},
  {role_id: 3, permission_id: 37},
  {role_id: 3, permission_id: 35},
  {role_id: 3, permission_id: 42},
  {role_id: 3, permission_id: 44},
  {role_id: 3, permission_id: 53},
  {role_id: 3, permission_id: 54},
  {role_id: 3, permission_id: 55},
  {role_id: 3, permission_id: 56},
  {role_id: 3, permission_id: 57},
  {role_id: 3, permission_id: 58}
])
