development:
  adapter: postgresql
  encoding: unicode
  database: food_delivery_dev
  pool: 5
  username: blira
  password: bryanlira

test:
  adapter: postgresql
  encoding: unicode
  database: food_delivery_test
  pool: 5
  username: blira
  password: bryanlira
